name: CMake-Linux-Coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  BUILD_TYPE: Coverage

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install xmllint for db test
      run: sudo apt update && sudo apt install libxml2-utils
    - name: Install lcov for coverage
      run: sudo apt update && sudo apt -y install lcov
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_TESTS=ON
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure
    - name: Collect coverage
      run: lcov --directory . --capture --output-file coverage.info && lcov --remove coverage.info '/usr/*' --output-file coverage.info
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
          fail_ci_if_error: true
          token: ${{secrets.CODECOV_TOKEN}}
          slug: CAHEK7/lensfun
          verbose: true
